version: '3.8'

services:
  hometier:
    build: .
    container_name: hometier
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    network_mode: host
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/inventory.db
    cap_add:
      - NET_ADMIN
      - NET_RAW