services:
  hometier:
    build: .
    container_name: hometier
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    privileged: true
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/inventory.db
    cap_add:
      - NET_ADMIN
      - NET_RAW