services:
  hometier:
    build: .
    container_name: hometier
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    privileged: true
    network_mode: host
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/inventory.db
      - PORT=${PORT:-5000}
    cap_add:
      - NET_ADMIN
      - NET_RAW